import { useAssetsPagesFunction } from './functionPages/AssetsPagesFunction';

export function AssetsPages() {
  const {
    assets,
    assetCategories,
    locations,
    form,
    loading,
    saving,
    error,
    createdEpc,
    isEditing,
    locationLocked,
    homeNeedsVerification,
    updateForm,
    loadPageData,
    handleEditAsset,
    handleCancelEdit,
    handleSubmitAsset,
  } = useAssetsPagesFunction();

  return (
    <div className="page">
      <div className="page-title-row">
        <div>
          <h2>Assets</h2>
          <p>Manage company asset master records.</p>
        </div>

        <button className="secondary-button" onClick={loadPageData}>
          Refresh
        </button>
      </div>

      {error && <div className="error-box">{error}</div>}
      {createdEpc && <div className="success-box">Asset registered successfully. Generated EPC: <strong>{createdEpc}</strong></div>}

      <form className="form-panel" onSubmit={handleSubmitAsset}>
        <div className="form-grid">
          <div className="form-field">
            <label>Asset Code</label>
            <input
              value={form.assetCode}
              onChange={(event) => updateForm("assetCode", event.target.value)}
              placeholder="Example: AST-0001"
            />
          </div>

          <div className="form-field">
            <label>Item Name</label>
            <input
              value={form.itemName}
              onChange={(event) => updateForm("itemName", event.target.value)}
              placeholder="Example: Dell Laptop"
            />
          </div>

          <div className="form-field">
            <label>Asset Category</label>
            <select
              value={form.categoryId}
              onChange={(event) => updateForm("categoryId", event.target.value)}
            >
              <option value="">Select Asset Category</option>
              {assetCategories.filter((category) => category.isActive).map((category) => (
                <option key={category.id} value={category.id}>
                  {category.categoryCode} — {category.name}
                </option>
              ))}
            </select>
          </div>

          <div className="form-field"><label>Measurement Height (mm)</label><input type="number" min="0" step="0.01" value={form.measurementHeight} onChange={(event) => updateForm("measurementHeight", event.target.value)} /></div>
          <div className="form-field"><label>Measurement Width (mm)</label><input type="number" min="0" step="0.01" value={form.measurementWidth} onChange={(event) => updateForm("measurementWidth", event.target.value)} /></div>

          {!isEditing && <>
            <div className="form-field checkbox-field"><label>EPC Registration</label><label className="checkbox-row"><input type="checkbox" checked={form.autoGenerateEpc} onChange={(event) => updateForm("autoGenerateEpc", event.target.checked)} />Auto Generate EPC</label></div>
            <div className="form-field"><label>EPC {form.autoGenerateEpc ? "(Generated by server)" : "(Manual)"}</label><input disabled={form.autoGenerateEpc} value={form.epcCode} onChange={(event) => updateForm("epcCode", event.target.value)} placeholder={form.autoGenerateEpc ? "Generated after registration" : "Paste or enter EPC"} /></div>
          </>}

          <div className="form-field">
            <label>{locationLocked ? "Current Verified Location (locked)" : "Registered / Home Storage Location"}</label>
            <select
              disabled={locationLocked}
              value={form.locationId}
              onChange={(event) => updateForm("locationId", event.target.value)}
            >
              <option value="">Select location</option>
              {locations.filter((location) => (locationLocked && String(location.id) === form.locationId) || (location.isActive && ["STORE", "WAREHOUSE", "RACK", "LEVEL", "BIN", "FILE"].includes(location.locationType))).map((location) => (
                <option key={location.id} value={location.id}>
                  {location.displayPath || location.name}
                </option>
              ))}
            </select>
          </div>

          {isEditing && locationLocked && <div className="form-field">
            <label>{homeNeedsVerification ? "Verify Registered / Home Storage Location" : "Registered / Home Storage Location (locked)"}</label>
            <select
              disabled={!homeNeedsVerification}
              required={homeNeedsVerification}
              value={form.homeLocationId}
              onChange={(event) => updateForm("homeLocationId", event.target.value)}
            >
              <option value="">{homeNeedsVerification ? "Select verified storage home" : "Verified"}</option>
              {locations.filter((location) => location.isActive && ["STORE", "WAREHOUSE", "RACK", "LEVEL", "BIN", "FILE"].includes(location.locationType)).map((location) => (
                <option key={location.id} value={location.id}>{location.displayPath || location.name}</option>
              ))}
            </select>
            {homeNeedsVerification && <small>Initializes the missing legacy home only; current verified location will not change.</small>}
          </div>}

          <div className="form-field">
            <label>Serial Number</label>
            <input
              value={form.serialNumber}
              onChange={(event) =>
                updateForm("serialNumber", event.target.value)
              }
              placeholder="Optional"
            />
          </div>

          <div className="form-field">
            <label>Brand</label>
            <input
              value={form.brand}
              onChange={(event) => updateForm("brand", event.target.value)}
              placeholder="Example: Dell"
            />
          </div>

          <div className="form-field">
            <label>Model</label>
            <input
              value={form.model}
              onChange={(event) => updateForm("model", event.target.value)}
              placeholder="Example: Latitude 5440"
            />
          </div>

          <div className="form-field">
            <label>Purchase Date</label>
            <input
              type="date"
              value={form.purchaseDate}
              onChange={(event) =>
                updateForm("purchaseDate", event.target.value)
              }
            />
          </div>

          <div className="form-field">
            <label>Purchase Cost</label>
            <input
              type="number"
              value={form.purchaseCost}
              onChange={(event) =>
                updateForm("purchaseCost", event.target.value)
              }
              placeholder="Example: 3500"
            />
          </div>

          <div className="form-field">
            <label>Condition</label>
            <select value={form.condition} onChange={(event) => updateForm("condition", event.target.value)}><option value="">Default: GOOD</option>{["NEW", "GOOD", "FAIR", "POOR", "DAMAGED"].map((condition) => <option key={condition} value={condition}>{condition}</option>)}</select>
          </div>

          <div className="form-field">
            <label>Remarks</label>
            <input
              value={form.remarks}
              onChange={(event) => updateForm("remarks", event.target.value)}
              placeholder="Optional"
            />
          </div>

          <div className="form-field checkbox-field">
            <label>Status Active</label>
            <label className="checkbox-row">
              <input
                type="checkbox"
                checked={form.isActive}
                onChange={(event) =>
                  updateForm("isActive", event.target.checked)
                }
              />
              Active
            </label>
          </div>
        </div>

        <div className="form-actions">
          <button className="primary-button" disabled={saving} type="submit">
            {saving
              ? "Saving..."
              : isEditing
              ? "Update Asset"
              : "Create Asset"}
          </button>

          {isEditing && (
            <button
              className="secondary-button"
              type="button"
              onClick={handleCancelEdit}
            >
              Cancel
            </button>
          )}
        </div>
      </form>

      <div className="table-panel">
        {loading ? (
          <p>Loading assets...</p>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Asset Code</th>
                <th>Item Name</th>
                <th>Category</th>
                <th>Measurement H × W</th>
                <th>EPC</th>
                <th>Location</th>
                <th>Status</th>
                <th>Condition</th>
                <th>Active</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {assets.length === 0 ? (
                <tr>
                  <td colSpan={11}>No assets found.</td>
                </tr>
              ) : (
                assets.map((asset) => (
                  <tr key={asset.id}>
                    <td>{asset.id}</td>
                    <td>{asset.assetCode}</td>
                    <td>{asset.itemName}</td>
                    <td>{asset.category?.name || asset.categoryId}</td>
                    <td>{asset.measurementHeight == null || asset.measurementWidth == null ? "-" : `${asset.measurementHeight} × ${asset.measurementWidth} mm`}</td>
                    <td>{asset.epc?.epcCode || "-"}</td>
                    <td>{asset.locationPath || asset.location?.name || "-"}</td>
                    <td>{asset.status ? asset.status.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) : "-"}</td>
                    <td>{asset.condition || "-"}</td>
                    <td>{asset.isActive === false ? "Inactive" : "Active"}</td>
                    <td>
                      <button
                        className="table-button"
                        type="button"
                        onClick={() => handleEditAsset(asset)}
                      >
                        Edit
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
