import type { Asset } from "../api/assets.api";
import { displayValue, formatBladeDetails, formatGap, formatMeasurement, formatPurchaseDate, formatRadius } from "../utils/assetDisplay";
import { locationDisplayName } from "../utils/locationDisplay";

const Field = ({ label, value }: { label: string; value: unknown }) => <div className="asset-detail-field"><small>{label}</small><strong>{displayValue(value)}</strong></div>;
export function AssetDetailsModal({ asset, close }: { asset: Asset | null; close: () => void }) {
  if (!asset) return null;
  return <div className="modal-backdrop"><div className="modal-card asset-details-modal" role="dialog" aria-modal="true" aria-labelledby="asset-details-title"><div className="page-title-row"><div><h3 id="asset-details-title">Asset Details</h3><p>{asset.assetCode} · Read-only master information</p></div><button type="button" className="secondary-button" onClick={close}>Close</button></div><section><h4>Basic Information</h4><div className="asset-detail-grid"><Field label="Asset Code" value={asset.assetCode} /><Field label="Item Name" value={asset.itemName} /><Field label="Category" value={asset.category?.name} /></div></section><section><h4>Measurement & Blade Details</h4><div className="asset-detail-grid"><Field label="Measurement" value={formatMeasurement(asset)} /><Field label="Blade Details" value={formatBladeDetails(asset)} /><Field label="Grid / Up" value={asset.gridUp == null ? null : `${asset.gridUp} UP`} /><Field label="Radius" value={formatRadius(asset.radius)} /><Field label="Gap" value={formatGap(asset.gapMm)} /></div></section><section><h4>Location</h4><div className="asset-detail-grid"><Field label="Current Location" value={locationDisplayName(asset.location)} /><Field label="Storage Location" value={locationDisplayName(asset.homeLocation)} /></div></section><section><h4>Identification</h4><div className="asset-detail-grid"><Field label="EPC" value={asset.epc?.epcCode} /><Field label="Brand" value={asset.brand} /><Field label="Model" value={asset.model} /><Field label="Serial Number" value={asset.serialNumber} /></div></section><section><h4>Purchase & Condition</h4><div className="asset-detail-grid"><Field label="Purchase Date" value={formatPurchaseDate(asset.purchaseDate)} /><Field label="Purchase Cost" value={asset.purchaseCost} /><Field label="Condition" value={asset.condition} /><Field label="Remarks" value={asset.remarks} /></div></section><section><h4>System</h4><div className="asset-detail-grid"><Field label="Status" value={asset.status} /><Field label="Active" value={asset.isActive === false ? "No" : "Yes"} /><Field label="Created At" value={asset.createdAt ? new Date(asset.createdAt).toLocaleString() : null} /><Field label="Updated At" value={asset.updatedAt ? new Date(asset.updatedAt).toLocaleString() : null} /></div></section></div></div>;
}
