import { useState } from "react";
import { toast } from "sonner";
import type { AssetCategory } from "../api/assetCategories.api";
import { importAssetsApi, validateAssetImportApi, type AssetImportRow, type AssetImportValidation } from "../api/assets.api";
import type { Location } from "../api/locations.api";
import { downloadAssetImportTemplate, parseAssetImportWorkbook } from "../utils/assetImportWorkbook";
import { Button } from "./ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "./ui/dialog";
import { Input } from "./ui/input";

type Props = { open: boolean; categories: AssetCategory[]; locations: Location[]; onOpenChange: (open: boolean) => void; onImported: () => Promise<void> };
const message = (error: unknown) => (error as { response?: { data?: { message?: string; data?: AssetImportValidation } }; message?: string }).response?.data?.message || (error as Error).message || "Import failed.";

export function AssetImportDialog({ open, categories, locations, onOpenChange, onImported }: Props) {
  const [rows, setRows] = useState<AssetImportRow[]>([]); const [validation, setValidation] = useState<AssetImportValidation | null>(null); const [clientErrors, setClientErrors] = useState<Map<number, string[]>>(new Map()); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [fileName, setFileName] = useState("");
  const mergedRows = validation?.rows.map(row => ({ ...row, errors: [...(clientErrors.get(row.sourceRow) || []), ...row.errors] })) || [];
  const valid = !!validation?.valid && clientErrors.size === 0;
  function close() { setRows([]); setValidation(null); setClientErrors(new Map()); setError(""); setFileName(""); onOpenChange(false); }
  async function choose(file?: File) { if (!file) return; setBusy(true); setError(""); setValidation(null); try { const parsed = await parseAssetImportWorkbook(file); setRows(parsed.rows); setClientErrors(parsed.clientErrors); setFileName(file.name); const result = await validateAssetImportApi(parsed.rows); setValidation(result); } catch (err) { setRows([]); setClientErrors(new Map()); setError(message(err)); } finally { setBusy(false); } }
  async function submit() { setBusy(true); setError(""); try { const result = await importAssetsApi(rows); if (!result.valid) { setValidation(result); setError("Resolve all row errors before importing."); return; } toast.success(`${result.importedCount} assets imported successfully.`); await onImported(); close(); } catch (err) { const response = (err as { response?: { data?: { data?: AssetImportValidation } } }).response?.data?.data; if (response) setValidation(response); setError(message(err)); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={value => { if (!busy) { if (value) onOpenChange(true); else close(); } }}><DialogContent className={`flex max-h-[90vh] w-[calc(100vw-2rem)] flex-col overflow-hidden ${validation ? "sm:!max-w-[1180px]" : "sm:!max-w-[680px]"}`}><DialogHeader className="shrink-0"><DialogTitle>Import Assets</DialogTitle><DialogDescription>Download the current template, complete the Assets sheet, then validate and import up to 500 new assets atomically.</DialogDescription></DialogHeader>
    <div className="flex flex-wrap items-center gap-3"><Button type="button" variant="outline" disabled={busy} onClick={() => void downloadAssetImportTemplate(categories, locations)}>Download XLSX Template</Button><Input className="max-w-sm" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={event => void choose(event.target.files?.[0])}/>{fileName && <span className="text-sm text-muted-foreground">{fileName}</span>}</div>
    {error && <div className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
    {validation && <div className="flex min-h-0 flex-1 flex-col gap-2"><p className="shrink-0 text-sm font-medium">{validation.rowCount} row(s): {mergedRows.filter(row => row.errors.length === 0).length} valid, {mergedRows.filter(row => row.errors.length > 0).length} invalid</p><div className="min-h-0 flex-1 overflow-auto rounded-md border"><table className="w-full min-w-[1100px] text-sm"><thead className="sticky top-0 z-10 bg-muted"><tr className="border-b"><th className="w-16 whitespace-nowrap p-2 text-left">Row</th><th className="min-w-36 whitespace-nowrap p-2 text-left">Asset Code</th><th className="min-w-44 p-2 text-left">Item Name</th><th className="min-w-36 whitespace-nowrap p-2 text-left">Category</th><th className="min-w-48 whitespace-nowrap p-2 text-left">Storage Location</th><th className="min-w-44 whitespace-nowrap p-2 text-left">EPC</th><th className="min-w-[300px] p-2 text-left">Status</th></tr></thead><tbody>{mergedRows.map(row => <tr key={row.sourceRow} className="border-b"><td className="whitespace-nowrap p-2">{row.sourceRow}</td><td className="whitespace-nowrap p-2">{row.assetCode || "—"}</td><td className="p-2">{row.itemName || "—"}</td><td className="whitespace-nowrap p-2">{row.categoryCode || "—"}</td><td className="whitespace-nowrap p-2">{row.storageLocationCode || "—"}</td><td className="whitespace-nowrap p-2">{row.epc || "—"}</td><td className={`min-w-[300px] whitespace-normal p-2 ${row.errors.length ? "text-destructive" : "text-emerald-700"}`}>{row.errors.length ? `Invalid: ${row.errors.join(" ")}` : "Valid"}</td></tr>)}</tbody></table></div></div>}
    <DialogFooter className="shrink-0"><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button><Button type="button" disabled={busy || !valid} onClick={() => void submit()}>{busy ? "Working..." : "Import Assets"}</Button></DialogFooter>
  </DialogContent></Dialog>;
}
